syntax = "proto3";

package admin.v1;

import "google/protobuf/field_mask.proto";

message FareRule {
  string id = 1;
  string fare_id = 2;
  optional string route_id = 3;
  optional string origin_id = 4;
  optional string destination_id = 5;
}

message ListFareRulesRequest {
  int32 page_size = 1;
  string page_token = 2;
}

message ListFareRulesResponse {
  repeated FareRule fare_rules = 1;
  string next_page_token = 2;
}

message GetFareRuleRequest {
  string id = 1;
}

message GetFareRuleResponse {
  FareRule fare_rule = 1;
}

message CreateFareRuleRequest {
  string fare_id = 1;
  optional string route_id = 2;
  optional string origin_id = 3;
  optional string destination_id = 4;
}

message CreateFareRuleResponse {
  FareRule fare_rule = 1;
}

message UpdateFareRuleRequest {
  string id = 1;
  string fare_id = 2;
  optional string route_id = 3;
  optional string origin_id = 4;
  optional string destination_id = 5;
  google.protobuf.FieldMask update_mask = 99;
}

message UpdateFareRuleResponse {
  FareRule fare_rule = 1;
}

message DeleteFareRuleRequest {
  string id = 1;
}

message DeleteFareRuleResponse {}

service FareRuleService {
  rpc ListFareRules(ListFareRulesRequest) returns (ListFareRulesResponse);
  rpc GetFareRule(GetFareRuleRequest) returns (GetFareRuleResponse);
  rpc CreateFareRule(CreateFareRuleRequest) returns (CreateFareRuleResponse);
  rpc UpdateFareRule(UpdateFareRuleRequest) returns (UpdateFareRuleResponse);
  rpc DeleteFareRule(DeleteFareRuleRequest) returns (DeleteFareRuleResponse);
}
