syntax = "proto3";

package admin.v1;

import "google/protobuf/field_mask.proto";
import "google/protobuf/timestamp.proto";

enum RoomFloor {
  ROOM_FLOOR_UNSPECIFIED = 0;
  ROOM_FLOOR_1 = 1;
  ROOM_FLOOR_2 = 2;
  ROOM_FLOOR_3 = 3;
  ROOM_FLOOR_4 = 4;
  ROOM_FLOOR_5 = 5;
  ROOM_FLOOR_6 = 6;
  ROOM_FLOOR_7 = 7;
  ROOM_FLOOR_VIRTUAL = 8;
}

message Room {
  string id = 1;
  string name = 2;
  RoomFloor floor = 3;
  google.protobuf.Timestamp created_at = 4;
  google.protobuf.Timestamp updated_at = 5;
}

message ListRoomsRequest {
  int32 page_size = 1;
  string page_token = 2;
}

message ListRoomsResponse {
  repeated Room rooms = 1;
  string next_page_token = 2;
}

message GetRoomRequest {
  string id = 1;
}

message GetRoomResponse {
  Room room = 1;
}

message CreateRoomRequest {
  string name = 1;
  RoomFloor floor = 2;
}

message CreateRoomResponse {
  Room room = 1;
}

message UpdateRoomRequest {
  string id = 1;
  string name = 2;
  RoomFloor floor = 3;
  google.protobuf.FieldMask update_mask = 99;
}

message UpdateRoomResponse {
  Room room = 1;
}

message DeleteRoomRequest {
  string id = 1;
}

message DeleteRoomResponse {}

service RoomService {
  rpc ListRooms(ListRoomsRequest) returns (ListRoomsResponse);
  rpc GetRoom(GetRoomRequest) returns (GetRoomResponse);
  rpc CreateRoom(CreateRoomRequest) returns (CreateRoomResponse);
  rpc UpdateRoom(UpdateRoomRequest) returns (UpdateRoomResponse);
  rpc DeleteRoom(DeleteRoomRequest) returns (DeleteRoomResponse);
}
